### ISSUE TITLE
building for iOS Simulator, but linking in object file built for iOS, for architecture arm64

### ISSUE THREAD

**Issue by virskor** [RxReader/tencent_kit#54]
building for iOS Simulator, but linking in object file built for iOS, for architecture arm64

flutter 2.5

**Comment by changleibox** [comment]
希望早日解决，我也遇到了，只有降级flutter版本了

**Comment by v7lin** [comment]
@virskor @changleibox 请自行检查一下有没有引入 flutter_bugly 插件
flutter_bugly 插件的 ios 里 podspec 少了一句
```
s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES', 'VALID_ARCHS[sdk=iphonesimulator*]' => 'x86_64' }
```

**Comment by v7lin** [comment]
其他解决方案 https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-object-file-built-for-ios

**Comment by v7lin** [comment]
试了试，最佳办法是修改 podfile
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    # 兼容 Flutter 2.5
    target.build_configurations.each do |config|
#       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386 arm64'
    end
  end
end
```

**Comment by virskor** [comment]
> 试了试，最佳办法是修改 podfile
> 
> ```
> 
> post_install do |installer|
> 
>   installer.pods_project.targets.each do |target|
> 
>     flutter_additional_ios_build_settings(target)
> 
>     # 兼容 Flutter 2.5
> 
>     target.build_configurations.each do |config|
> 
> #       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
> 
>       config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386 arm64'
> 
>     end
> 
>   end
> 
> end
> 
> ```

我也是改成你这样好了

**Comment by cubegao** [comment]
xcode 直接运行没问题，flutter run 就报错

**Comment by suyie001** [comment]
能运行是能运行了，但是模拟器变得超级卡了。。。如果不用这个插件的话就很流畅
