### ISSUE TITLE
flutter升级到2.5.1以后ios模拟器运行报错

### ISSUE THREAD

**Issue by luoweii** [RxReader/tencent_kit#57]
ld: in /Users/luowei/work/Flutter/SDK/flutter/.pub-cache/hosted/pub.dartlang.org/tencent_kit-2.1.0/ios/Libraries/TencentOpenAPI.framework/TencentOpenAPI(QQObject.o), building for iOS Simulator, but linking in object file built for iOS, for architecture arm64

**Comment by v7lin** [comment]
见 [issues/54](https://github.com/RxReader/tencent_kit/issues/54)
