### ISSUE TITLE
可以更新到3.5.7吗?

### ISSUE THREAD

**Issue by badboy-tian** [RxReader/tencent_kit#62]
最新版sdk更新到了3.5.7, 然后做了隐私合规
![image](https://user-images.githubusercontent.com/2835129/143727462-82c6f266-4c51-4155-9551-62b6f6847fca.png)
https://wiki.connect.qq.com/sdk%e4%b8%8b%e8%bd%bd

**Comment by flutterbest** [comment]
3.5.9，我提过pr了 最新代码在我仓库
