### ISSUE TITLE
兼容dart 2.15.0虚拟机问题

### ISSUE THREAD

**Issue by luokunman** [RxReader/tencent_kit#70]
虚拟机运行xcode报错
```
ld: in /Users/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/tencent_kit-2.1.0/ios/Libraries/TencentOpenAPI.framework/TencentOpenAPI(QQObject.o), 
building for iOS Simulator, but linking in object file built for iOS, for architecture arm64

```
[✓] Flutter (Channel stable, 2.8.0, on macOS 11.4 20F71 darwin-arm, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[!] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    ! Flutter recommends a minimum Xcode version of 13.0.0.
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.57.1)
[✓] Connected device (3 available)
```

**Comment by luokunman** [comment]
我重新打开该issue
因为我需要在该插件打开arm64 架构

**Comment by v7lin** [comment]
[issues#54](https://github.com/RxReader/tencent_kit/issues/54)
