### ISSUE TITLE
分享到QQ好友，每次新安装完应用，第一次打不开QQ，再试就可以打开QQ了

### ISSUE THREAD

**Issue by horo99** [RxReader/tencent_kit#79]
不过控制台每次都会提示这个 1003
```
2022-06-09:07:46:16:815 [QQAPI] ApiTool.m:534 on +[TcApiTool openUniversallinkIfNeed:], use univeral link, ifneed=0 sdkcfg=0 apicheck=1
Connection 22: received failure notification
Connection 22: failed to connect 12:8, reason -1
Connection 22: encountered error(12:8)
Task <D177F2FD-8BE3-4B6B-BD26-622B4F3A20A4>.<0> HTTP load failed, 0/0 bytes (error code: -1003 [12:8])
NSURLConnection finished with error - code -1003
```

**Comment by horo99** [comment]
安卓上好好的，可是 ios 上第一次调用shareWebpage没反应也没有报错，等到第二次调用才能打开QQ。

**Comment by horo99** [comment]
更进一步了解了，如果是先调用 `registerApp` 然后 `setIsPermissionGranted` ，那么调用 `shareWebpage` 不会打开QQ也没有任何反馈。
交换一下代码顺序，要先调用 `setIsPermissionGranted` 然后再调用 `registerApp` 就可以正常打开QQ了。
这是什么鬼bug，也只有我这样优秀的人才才能发现！！

**Comment by v7lin** [comment]
[example/lib/main.dart](https://github.com/RxReader/tencent_kit/blob/master/example/lib/main.dart)
```dart
          ListTile(
            title: Text('3.1.0 之后的版本请先获取权限'),
            onTap: () async {
              await Tencent.instance.setIsPermissionGranted(granted: true);
              _showTips('授权', '已授权获取设备信息/同意隐私协议');
            },
          ),
```

[Android_SDK环境搭建](https://wiki.connect.qq.com/qq%e7%99%bb%e5%bd%95)

```
2. 初始化SDK
3.5.7版本新增接口提供用户设置是否已授权获取设备信息，在调用互联SDK相关功能接口之前，需要应用在确认用户已授权应用获取设备信息后，调用下面代码通知 SDK：

Tencent.setIsPermissionGranted(true);

如果未调用该接口或传参为false时，调用其它功能接口将直接返回失败。

3.5.9版本中可以调用Tencent.setisPermissionGranted(true, Build.Model)传入Build.Model，传入后SDK内部不再自行获取。
```

[iOS_SDK环境搭建](https://wiki.connect.qq.com/ios_sdk%e7%8e%af%e5%a2%83%e6%90%ad%e5%bb%ba)

```
4.5设置用户是否同意隐私协议。
3.5.7版本更新后，在初始化SDK之前必须设置用户同意授权隐私协议，如果没有设置或者设置为NO（不同意）则无法使用SDK的接口，设置方式如下：

[TencentOAuth setIsUserAgreedAuthorization:YES];
```

**Comment by zzy080615** [comment]
> 更进一步了解了，如果是先调用 `registerApp` 然后 `setIsPermissionGranted` ，那么调用 `shareWebpage` 不会打开QQ也没有任何反馈。
> 交换一下代码顺序，要先调用 `setIsPermissionGranted` 然后再调用 `registerApp` 就可以正常打开QQ了。
> 这是什么鬼bug？
> 我真TM是个人才！



> 更进一步了解了，如果是先调用 `registerApp` 然后 `setIsPermissionGranted` ，那么调用 `shareWebpage` 不会打开QQ也没有任何反馈。
> 交换一下代码顺序，要先调用 `setIsPermissionGranted` 然后再调用 `registerApp` 就可以正常打开QQ了。
> 这是什么鬼bug？
> 我真TM是个人才！

真tm的是个天才
