### ISSUE TITLE
IOS模拟器运行arm64错误

### ISSUE THREAD

**Issue by zzg19901210** [RxReader/tencent_kit#80]
g/.pub-cache/hosted/pub.flutter-io.cn/tencent_kit-4.0.0/ios/Libraries/TencentOpenAPI.framework/TencentOpenAPI(QQApiAudioObject.o), building for iOS Simulator, but linking in object file built for iOS, for architecture arm64

**Comment by v7lin** [comment]
能否给出更具体的日志 ... 我这边用的都好好的 ...

**Comment by Leoxxx404** [comment]
同问m2芯片

**Comment by Leoxxx404** [comment]
> g/.pub-cache/hosted/pub.flutter-io.cn/tencent_kit-4.0.0/ios/Libraries/TencentOpenAPI.framework/TencentOpenAPI(QQApiAudioObject.o), building for iOS Simulator, but linking in object file built for iOS, for architecture arm64

在xcode里面把tencent_kit的Excluded Architectures 增加 arm64， 本来带有arm64的 我又改了一遍  => 编译通过

**Comment by v7lin** [comment]
唉，认真看一遍 README.md 就那么难么 ...
相同的BUG[issues/54](https://github.com/RxReader/tencent_kit/issues/54)
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    # 兼容 Flutter 2.5
    target.build_configurations.each do |config|
#       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386 arm64'
    end
  end
end
```

**Comment by Leoxxx404** [comment]
一开始就设置了 没起作用
