### ISSUE TITLE
mac m1芯片编译报错

### ISSUE THREAD

**Issue by PeterQF** [RxReader/tencent_kit#83]
Error (Xcode): In /Users/peter/sdk/flutter/.pub-cache/hosted/pub.flutter-io.cn/tencent_kit-4.0.0/ios/Libraries/TencentOpenAPI.framework/TencentOpenAPI(libTencentOpenApi_IOS.a-arm64-master.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/peter/sdk/flutter/.pub-cache/hosted/pub.flutter-io.cn/tencent_kit-4.0.0/ios/Libraries/TencentOpenAPI.framework/TencentOpenAPI'

Could not build the application for the simulator.
Error launching application on iPhone 14 Pro.

**Comment by easonccc** [comment]
和你一样的报错 请问解决了吗
